{
 "title": "Sungrow Grid Tie",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Real-time Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Load power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Load.power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "W" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real-time Production",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Total active power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Total.active.power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "W" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real-time Consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Feeder power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Feeder.power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "W" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power produced today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Daily power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Daily.power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "kWh" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total power produced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Total power yield",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Total.power.yield/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "kWh" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total run time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Total running time",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Total.running.time/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "hours" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Internal temperature",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Internal.temperature/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "C" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy Consumed Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "Load power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Load.power/)\r\n  |> integral(unit: 3600s)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])\r\n",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy Produced Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "Total active power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Total.active.power/)\r\n  |> integral(unit: 3600s)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Energy Consumption Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "Feeder power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Feeder.power/)\r\n  |> integral(unit: 3600s)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Work state",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Work.state/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "code" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Working state 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Work state 2",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Work.state.2/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "code" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Household Load and Feeder Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "Load power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Load.power|Feeder.power/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])\r\n\r\n",
     "select": [
      [
       { "params": [ "W" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Feeder power",
     "select": [
      [
       { "params": [ "W" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Phase A Voltage and  Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "measurement": "Phase A voltage",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Phase.A/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "V" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Phase A current",
     "select": [
      [
       { "params": [ "A" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Input/Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "Total DC power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Total.DC.power|Total.active.power/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "W" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Total active power",
     "select": [
      [
       { "params": [ "W" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MPPT Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "measurement": "DC current of MPPT1",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /DC.current.of.MPPT/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "A" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "DC current of MPPT2",
     "select": [
      [
       { "params": [ "A" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MPPT Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "measurement": "DC voltage of MPPT1",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /DC.voltage.of.MPPT/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "V" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "DC voltage of MPPT2",
     "select": [
      [
       { "params": [ "V" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MPPT Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "DC voltage of MPPT1",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /DC.voltage.of.MPPT/)\r\n  |> aggregateWindow(every: 5m, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "V" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /DC.current.of.MPPT/)\r\n  |> aggregateWindow(every: 5m, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Impedance to ground",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kohm" } },
   "targets": [
    {
     "measurement": "Impedance to ground",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Impedance.to.ground/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "kOhms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reactive power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "targets": [
    {
     "measurement": "Nominal reactive output power",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Nominal.reactive.output.power/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "kvar" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "measurement": "Grid frequency",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Grid.frequency/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "Hz" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "measurement": "Power factor",
     "query": "from(bucket: \"Sungrow\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Power.factor/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "%" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}